
#Sudo permissons required
sudo: required

#Describe services
services:
  - docker #We will use docker
  
before_install:
  - docker build -t emmc89/docker-react -f Dockerfile.dev . #build docker with tag

script:
  - docker run emmc89/docker-react npm run test -- --coverage 
    #run the test and end it

deploy:
  provider: elasticbeanstalk #use it set of instruction for deploy
  region: "us-west-2" #region of aws
  app: "Docker" #name
  env: "Docker-env" #name
  bucket_name: "elasticbeanstalk-us-west-2-336142811313"
  bucket_path: "Docker"
  on:
    branch: master #just deploy from master branch
    access_key_id: "$AWS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET" #AWS Access IAM
